package cn.codecrab.plugins.dsh

import com.intellij.ide.AppLifecycleListener
import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.diagnostic.Logger
import java.io.File

/**
 * dsh 进程管理器 (应用级单例)。
 *
 * 支持两种启动方式 (见设置):
 *  - WSL 模式: 通过 `wsl.exe bash` 在 WSL 中运行 dsh (通用化: 自动加载用户 ~/.bashrc,
 *    因此 nvm/常规 PATH 安装的 dsh 都能直接用, 不再绑定任何本机路径)
 *  - Windows 模式: 直接在 Windows 上以隐藏窗口运行 `dsh web`
 *
 * 进程隐藏后台运行 (PowerShell -WindowStyle Hidden 包裹, 不弹控制台窗口),
 * 输出捕获到工具窗口日志面板, 轮询端口等待 WebUI 就绪。
 *
 * 退出清理三层保障, 避免 "IDE 退出了 dsh 还在后台":
 *  1. AppLifecycleListener.appClosing — IDEA 退出流程早期回调, 应用服务仍可用
 *  2. JVM shutdown hook — 兜底 (即使 appClosing 没触发)
 *  3. 独立看门狗进程 — 监视 IDE 进程, IDE 消失且端口仍开时自动执行停止脚本
 *     (即使 IDE 被强杀/崩溃, dsh 也会被清理)
 */
object DshServer {

    private val LOG = Logger.getInstance(DshServer::class.java)

    enum class State { IDLE, STARTING, RUNNING, STOPPING }

    @Volatile
    var state: State = State.IDLE
        private set

    @Volatile
    private var process: Process? = null

    /** 启动时预生成的停止脚本路径 (WSL: pkill; Windows: taskkill), 退出清理复用 */
    @Volatile
    private var stopCmdPath: String? = null

    private val lock = Any()

    init {
        // 1) IDEA 退出流程早期回调 (服务仍可用, 最可靠的清理时机)
        try {
            ApplicationManager.getApplication().messageBus.connect().subscribe(
                AppLifecycleListener.TOPIC,
                object : AppLifecycleListener {
                    override fun appClosing() {
                        stopOnExit()
                    }
                }
            )
        } catch (_: Throwable) {
        }
        // 2) JVM shutdown hook 兜底
        Runtime.getRuntime().addShutdownHook(Thread({ stopOnExit() }, "dsh-plugin-shutdown"))
    }

    fun webUrl(port: Int): String = "http://localhost:$port/"

    fun isRunning(): Boolean = state == State.RUNNING

    /**
     * 启动 dsh。
     *
     * @param projectPath 当前项目根路径
     * @param onLog       日志回调 (任意线程, 调用方负责切到 EDT)
     * @param onState     状态变化回调 (任意线程)
     */
    fun start(projectPath: String?, onLog: (String) -> Unit, onState: (State) -> Unit) {
        val settings = DshSettingsState.getInstance()
        val port = settings.port
        if (port !in 1..65535) {
            onLog("端口配置无效: $port (应为 1-65535), 请检查设置")
            return
        }
        synchronized(lock) {
            if (state == State.STARTING || state == State.RUNNING) {
                onLog("dsh 已在运行 (state=${state.name})")
                return
            }
            if (WslSupport.isPortOpen(port)) {
                onLog("端口 $port 已有服务在监听, 直接打开 WebUI (不重复启动)")
                state = State.RUNNING
                onState(state)
                return
            }
            state = State.STARTING
            onState(state)
            try {
                launch(projectPath, port, settings, onLog, onState)
            } catch (t: Throwable) {
                LOG.warn("launch dsh failed", t)
                onLog("启动失败: ${t.message}")
                state = State.IDLE
                onState(state)
            }
        }
    }

    private fun launch(
        projectPath: String?,
        port: Int,
        settings: DshSettingsState,
        onLog: (String) -> Unit,
        onState: (State) -> Unit,
    ) {
        val mode = settings.launchMode
        when (mode) {
            "windows" -> launchOnWindows(projectPath, port, settings, onLog, onState)
            else -> {
                if (!WslSupport.isWindows) {
                    onLog("WSL 模式仅在 Windows + WSL 环境下可用, 请到设置中改用「Windows 直接启动」")
                    state = State.IDLE
                    onState(state)
                    return
                }
                launchOnWsl(projectPath, port, settings, onLog, onState)
            }
        }
    }

    // ---------- WSL 启动 ----------

    private fun launchOnWsl(
        projectPath: String?,
        port: Int,
        settings: DshSettingsState,
        onLog: (String) -> Unit,
        onState: (State) -> Unit,
    ) {
        val wslProject = WslSupport.toWslPath(projectPath)
        val extra = settings.extraDshArgs.trim()

        // 1) WSL 侧启动脚本 (通用: 加载用户 ~/.bashrc, nvm 或 PATH 安装的 dsh 均可)
        val shFile = WslSupport.createTempFile("dsh-run-wsl-", ".sh")
        val shWslPath = WslSupport.toWslPath(shFile.absolutePath) ?: shFile.absolutePath
        val shContent = buildString {
            appendLine("#!/usr/bin/env bash")
            appendLine("# Generated by Dsh plugin. Do not edit.")
            if (wslProject != null) {
                appendLine("if [ -d ${WslSupport.shellSingleQuote(wslProject)} ]; then")
                appendLine("  cd ${WslSupport.shellSingleQuote(wslProject)} 2>/dev/null || cd \"\$HOME\" || exit 1")
                appendLine("else")
                appendLine("  echo \"[dsh] WARNING: 项目目录不存在: ${WslSupport.shellSingleQuote(wslProject)}\", 回退到 \$HOME")
                appendLine("  cd \"\$HOME\" || exit 1")
                appendLine("fi")
            } else {
                appendLine("cd \"\$HOME\" || exit 1")
            }
            // 通用环境初始化: 外层 bash 使用 -lic (登录+交互), 等价于用户自己的终端环境,
            // 完整加载 ~/.profile 与 ~/.bashrc (nvm 等放在 .bashrc 里也能生效);
            // 这里再兜底从 NVM_DIR 或 ~/.nvm 直接加载 nvm (不硬编码任何路径)
            appendLine("[ -s \"\$HOME/.profile\" ] && . \"\$HOME/.profile\" >/dev/null 2>&1 || true")
            appendLine("if ! command -v node >/dev/null 2>&1; then")
            appendLine("  if [ -s \"\${NVM_DIR:-\$HOME/.nvm}/nvm.sh\" ]; then")
            appendLine("    . \"\${NVM_DIR:-\$HOME/.nvm}/nvm.sh\" >/dev/null 2>&1 || true")
            appendLine("    nvm use default >/dev/null 2>&1 || true")
            appendLine("  fi")
            appendLine("fi")
            appendLine("if ! command -v dsh >/dev/null 2>&1; then")
            appendLine("  echo \"[dsh] WARNING: 在 WSL 中找不到 dsh 命令 (请确认 PATH 或已通过 nvm 安装)\"")
            appendLine("fi")
            appendLine("echo \"[dsh] starting dsh web  (project: ${wslProject ?: "\$HOME"}, port: $port)\"")
            if (extra.isNotEmpty()) {
                appendLine("exec dsh web --port $port $extra")
            } else {
                appendLine("exec dsh web --port $port")
            }
        }
        WslSupport.writeTextFile(shFile, shContent)
        onLog("WSL 模式: 已生成启动脚本 ${shFile.name}")

        val cmdFile = WslSupport.createTempFile("dsh-run-wsl-", ".cmd")
        // bash -lic: 登录 + 交互, 完整加载用户 shell 配置 (nvm 依赖交互式初始化)
        WslSupport.writeTextFile(
            cmdFile,
            "@echo off\r\nsetlocal\r\nwsl.exe bash -lic \"bash ${WslSupport.shellSingleQuote(shWslPath)}\"\r\n",
            crlf = true
        )
        onLog("wsl 工作目录: ${wslProject ?: "(WSL HOME)"}  (项目空间默认使用当前项目根路径)")
        startWrapper(cmdFile, onLog, port, onState, "wsl")
    }

    // ---------- Windows 直接启动 ----------

    private fun launchOnWindows(
        projectPath: String?,
        port: Int,
        settings: DshSettingsState,
        onLog: (String) -> Unit,
        onState: (State) -> Unit,
    ) {
        val extra = settings.extraDshArgs.trim()
        if (!WslSupport.isWindows) {
            // macOS/Linux: 直接用 bash 启动
            val shFile = WslSupport.createTempFile("dsh-run-posix-", ".sh")
            val cwd = projectPath?.let { if (File(it).isDirectory) it else null }
            val content = buildString {
                appendLine("#!/usr/bin/env bash")
                if (cwd != null) appendLine("cd ${WslSupport.shellSingleQuote(cwd)} 2>/dev/null || exit 1")
                appendLine("if ! command -v dsh >/dev/null 2>&1; then")
                appendLine("  echo \"[dsh] WARNING: 在 PATH 中找不到 dsh 命令 (npm i -g @deepseek-ai/dsh)\"")
                appendLine("fi")
                if (extra.isNotEmpty()) appendLine("exec dsh web --port $port $extra") else appendLine("exec dsh web --port $port")
            }
            WslSupport.writeTextFile(shFile, content)
            val p = ProcessBuilder("bash", shFile.absolutePath).start()
            process = p
            drain(p, onLog)
            watch(p, port, onLog)
            waitForReadyInThread(port, p, onLog, onState)
            return
        }

        val cmdFile = WslSupport.createTempFile("dsh-run-win-", ".cmd")
        val content = buildString {
            appendLine("@echo off")
            appendLine("setlocal")
            if (projectPath != null && File(projectPath).isDirectory) {
                appendLine("cd /d \"$projectPath\"")
            }
            appendLine("where dsh >nul 2>&1")
            appendLine("if errorlevel 1 (")
            appendLine("  echo [dsh] WARNING: 在 Windows PATH 中找不到 dsh 命令")
            appendLine("  echo [dsh] 请先安装: npm i -g @deepseek-ai/dsh")
            appendLine(")")
            if (extra.isNotEmpty()) {
                appendLine("dsh web --port $port $extra")
            } else {
                appendLine("dsh web --port $port")
            }
        }
        WslSupport.writeTextFile(cmdFile, content, crlf = true)
        onLog("Windows 模式: 已生成启动命令 ${cmdFile.name}")
        onLog("工作目录: ${if (projectPath != null && File(projectPath).isDirectory) projectPath else "(缺省)"}  (项目空间默认使用当前项目根路径)")
        startWrapper(cmdFile, onLog, port, onState, "windows")
    }

    /** 通过隐藏的 PowerShell 执行 .cmd, 并挂上输出/进程 watching 和端口轮询 */
    private fun startWrapper(cmdFile: File, onLog: (String) -> Unit, port: Int, onState: (State) -> Unit, mode: String) {
        val launchCmd = listOf(
            "powershell.exe",
            "-NoProfile",
            "-ExecutionPolicy", "Bypass",
            "-WindowStyle", "Hidden",
            "-Command", "& '${cmdFile.absolutePath}'",
        )
        onLog("启动命令: powershell.exe -WindowStyle Hidden -> ${cmdFile.name}")
        val p = ProcessBuilder(launchCmd).start()
        process = p
        // 预生成停止脚本 + 启动退出看门狗, 保证 IDE 无论怎么退出 dsh 都能被清理
        stopCmdPath = prepareStopScript(port, mode)
        startExitWatchdog(stopCmdPath!!, port)
        drain(p, onLog)
        watch(p, port, onLog)
        waitForReadyInThread(port, p, onLog, onState)
    }

    // ---------- 输出 / 生命周期 ----------

    private fun drain(p: Process, onLog: (String) -> Unit) {
        fun reader(stream: java.io.InputStream, tag: String) {
            Thread({
                try {
                    stream.bufferedReader(Charsets.UTF_8).useLines { lines ->
                        for (line in lines) onLog("$tag $line")
                    }
                } catch (_: Exception) {
                }
            }, "dsh-plugin-$tag-reader").apply { isDaemon = true }.start()
        }
        reader(p.inputStream, "[dsh]")
        reader(p.errorStream, "[dsh!]")
    }

    private fun watch(p: Process, port: Int, onLog: (String) -> Unit) {
        Thread({
            try {
                val code = p.waitFor()
                LOG.info("dsh launcher exited with code $code")
                if (state == State.STARTING || state == State.RUNNING) {
                    if (WslSupport.isPortOpen(port)) {
                        onLog("启动包装进程已退出(exit=$code), 但端口 $port 仍在监听, 保持连接")
                    } else {
                        onLog("dsh 进程已退出 (exit=$code)")
                        state = State.IDLE
                    }
                }
            } catch (_: InterruptedException) {
            }
        }, "dsh-plugin-watchdog").apply { isDaemon = true }.start()
    }

    private fun waitForReadyInThread(port: Int, p: Process, onLog: (String) -> Unit, onState: (State) -> Unit) {
        Thread({ waitForReady(port, p, onLog, onState) }, "dsh-plugin-port-poll").apply { isDaemon = true }.start()
    }

    private fun waitForReady(port: Int, p: Process, onLog: (String) -> Unit, onState: (State) -> Unit) {
        val deadline = System.currentTimeMillis() + 120_000
        while (System.currentTimeMillis() < deadline) {
            if (Thread.currentThread().isInterrupted) return
            synchronized(lock) {
                if (state == State.IDLE || state == State.STOPPING) return
            }
            if (WslSupport.isPortOpen(port)) {
                synchronized(lock) {
                    if (state == State.STOPPING) return
                    state = State.RUNNING
                }
                onLog("WebUI 就绪: ${webUrl(port)}")
                onState(State.RUNNING)
                return
            }
            if (!p.isAlive) {
                onLog("启动进程已退出, 端口 $port 未就绪, 请查看上方日志排查")
                synchronized(lock) {
                    if (state == State.STARTING) state = State.IDLE
                }
                onState(State.IDLE)
                return
            }
            try {
                Thread.sleep(700)
            } catch (_: InterruptedException) {
                return
            }
        }
        onLog("等待 $port 端口就绪超时 (120s), dsh 可能未启动成功")
        synchronized(lock) {
            if (state == State.STARTING) state = State.IDLE
        }
        onState(State.IDLE)
    }

    /**
     * 停止 dsh。
     *  - WSL 模式: 在 WSL 内 pkill 该端口的 dsh 进程 (不影响其他 WSL 会话)
     *  - Windows 模式: taskkill 终止包装进程树
     */
    fun stop(onLog: (String) -> Unit, onState: (State) -> Unit) {
        synchronized(lock) {
            if (state == State.IDLE || state == State.STOPPING) {
                onLog("当前没有运行中的 dsh (state=${state.name})")
                return
            }
            state = State.STOPPING
            onState(state)
            Thread({
                try {
                    runStopScript(onLog)
                    Thread.sleep(500)
                    onLog("已发送停止信号")
                } catch (t: Throwable) {
                    LOG.warn("stop dsh failed", t)
                    onLog("停止过程出错: ${t.message}")
                } finally {
                    try {
                        process?.destroy()
                    } catch (_: Exception) {
                    }
                    process = null
                    stopCmdPath = null
                    state = State.IDLE
                    onState(state)
                }
            }, "dsh-plugin-stop").apply { isDaemon = true }.start()
        }
    }

    /**
     * 预生成停止脚本并返回其路径。
     *  - WSL 模式: pkill 精确匹配端口 (括号技巧避免匹配到自身命令行)
     *  - Windows 模式: taskkill 终止启动包装进程树
     */
    private fun prepareStopScript(port: Int, mode: String): String {
        return if (mode == "windows") {
            val pid = process?.pid() ?: 0L
            val cmd = WslSupport.createTempFile("dsh-stop-", ".cmd")
            WslSupport.writeTextFile(cmd, "@echo off\r\ntaskkill /PID $pid /T /F >nul 2>&1\r\n", crlf = true)
            cmd.absolutePath
        } else {
            val stopSh = WslSupport.createTempFile("dsh-stop-", ".sh")
            val stopShWsl = WslSupport.toWslPath(stopSh.absolutePath) ?: stopSh.absolutePath
            val pattern = "[w]eb --port $port([^0-9]|\$)"
            WslSupport.writeTextFile(
                stopSh,
                "pkill -f '$pattern' || true\nsleep 1\npkill -9 -f '$pattern' || true\n"
            )
            val cmd = WslSupport.createTempFile("dsh-stop-", ".cmd")
            WslSupport.writeTextFile(
                cmd,
                "@echo off\r\nsetlocal\r\nwsl.exe bash -lc \"bash '${stopShWsl}'\"\r\n",
                crlf = true
            )
            cmd.absolutePath
        }
    }

    /** 通过隐藏 PowerShell 执行停止脚本 */
    private fun runStopScript(onLog: (String) -> Unit) {
        val stopPath = stopCmdPath ?: run {
            val settings = DshSettingsState.getInstance()
            prepareStopScript(settings.port, settings.launchMode)
        }
        try {
            ProcessBuilder(
                "powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass",
                "-WindowStyle", "Hidden",
                "-Command", "& '${stopPath}'",
            ).start().waitFor(15, java.util.concurrent.TimeUnit.SECONDS)
        } catch (t: Throwable) {
            LOG.warn("run stop script failed", t)
            onLog("停止脚本执行失败: ${t.message}")
        }
    }

    /**
     * 退出看门狗: 独立的隐藏 PowerShell 进程。
     *  - 若 IDE 进程消失 (正常退出/强杀/崩溃) 且端口仍开 → 执行停止脚本
     *  - 若端口已关闭 (正常停止过) → 自行退出, 不残留
     */
    private fun startExitWatchdog(stopPath: String, port: Int) {
        try {
            val idePid = ProcessHandle.current().pid()
            val script = buildString {
                append("\$ppid=$idePid; \$stop='$stopPath'; \$port=$port; ")
                append("while(\$true){ ")
                append("if(-not (Get-Process -Id \$ppid -ErrorAction SilentlyContinue)){ & \$stop | Out-Null; exit }; ")
                append("\$c=New-Object Net.Sockets.TcpClient; ")
                append("try{ \$c.Connect('127.0.0.1',\$port); \$c.Close() }catch{ exit }; ")
                append("Start-Sleep -Seconds 5 ")
                append("}")
            }
            ProcessBuilder(
                "powershell.exe", "-NoProfile", "-WindowStyle", "Hidden",
                "-Command", script,
            ).start()
        } catch (t: Throwable) {
            LOG.warn("start exit watchdog failed", t)
        }
    }

    /**
     * IDE 退出时的静默清理 (无 UI 回调)。appClosing 与 JVM shutdown hook 都会调用, 幂等。
     */
    private fun stopOnExit() {
        try {
            val stopPath = stopCmdPath ?: run {
                var port = 3090
                var mode = "wsl"
                try {
                    val s = DshSettingsState.getInstance()
                    port = s.port
                    mode = s.launchMode
                } catch (_: Throwable) {
                }
                prepareStopScript(port, mode)
            }
            try {
                ProcessBuilder(
                    "powershell.exe", "-NoProfile", "-WindowStyle", "Hidden",
                    "-Command", "& '${stopPath}'",
                ).start().waitFor(15, java.util.concurrent.TimeUnit.SECONDS)
            } catch (_: Throwable) {
            }
            try {
                process?.destroy()
            } catch (_: Throwable) {
            }
        } catch (_: Throwable) {
            // 退出阶段忽略所有异常
        }
    }
}